name: Auto Merge PRs

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled, ready_for_review]
  check_suite:
    types: [completed]
  workflow_run:
    workflows: ["CI"]
    types: ["completed"]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge labeled PRs when checks pass
        uses: peter-evans/auto-merge@v3
        with:
          merge-method: squash
          commit-message: pull-request-title
          required-labels: automerge
          delete-branch: true

